FROM quay.io/refgenomics/docker-ubuntu:14.04

MAINTAINER Cate McMahon <cmcmahon24@kgi.edu>

RUN apt-get install -y bwa
RUN apt-get install -y samtools
RUN apt-get install -y bcftools

# Convenience commands
ADD ../Scripts/CRISPR_Project.ipynb CRISPR_Project.ipynb
RUN chmod +x CRISPR_Project.ipynb